import { useEffect, useRef, useState } from 'react';
import type { VerovioToolkit } from 'verovio/esm';
import type { Query } from '../types';
import { toMEI } from '../music/mei';
let modulePromise:Promise<[typeof import('verovio/wasm'),typeof import('verovio/esm')]>|null=null;
const makeToolkit=()=>{modulePromise??=Promise.all([import('verovio/wasm'),import('verovio/esm')]);return modulePromise.then(async([wasm,esm])=>new esm.VerovioToolkit(await wasm.default()))};
export function Notation({query,activeId,highlightIds=[],onSelect,onPitchChange,full=false}:{query:Query;activeId?:string;highlightIds?:string[];onSelect?:(id:string)=>void;onPitchChange?:(id:string,semitones:number)=>void;full?:boolean}){const [svg,setSvg]=useState(''),[cursor,setCursor]=useState<number|null>(null);const drag=useRef<{id:string;y:number}|null>(null),root=useRef<HTMLDivElement>(null),toolkit=useRef<Promise<VerovioToolkit>|null>(null);if(!toolkit.current)toolkit.current=makeToolkit();
 useEffect(()=>{let live=true;if(!query.events.length){setSvg('');return;}toolkit.current!.then(tk=>{tk.setOptions({pageWidth:1400,pageHeight:full?50000:300,scale:48,adjustPageHeight:true,breaks:full?'auto':'none',svgViewBox:true,measureNumbers:1});tk.loadData(toMEI(query));let output=tk.renderToSVG(1,false);for(const id of highlightIds)output=output.replace(`id="${id}"`,`id="${id}" data-matched="true"`);if(activeId)output=output.replace(`id="${activeId}"`,`id="${activeId}" data-selected="true"`);if(live)setSvg(output)}).catch(()=>setSvg(''));return()=>{live=false}},[query,activeId,highlightIds.join('|'),full]);
 useEffect(()=>{if(!activeId){setCursor(null);return}requestAnimationFrame(()=>{const host=root.current,note=host?.querySelector(`[id="${CSS.escape(activeId)}"]`);if(host&&note){const h=host.getBoundingClientRect(),n=note.getBoundingClientRect();setCursor(n.left-h.left+n.width/2)}})},[svg,activeId]);
 const noteId=(target:EventTarget|null)=>(target as Element|null)?.closest?.('g.note')?.id||'';
 return <div ref={root} className={`notation ${onSelect?'editable':''} ${full?'full-notation':''}`} aria-label="Verovio 악보 미리보기" onPointerDown={e=>{const id=noteId(e.target);if(id){drag.current={id,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}}} onPointerUp={e=>{const d=drag.current;if(!d)return;const steps=Math.round((d.y-e.clientY)/6);drag.current=null;if(steps)onPitchChange?.(d.id,steps);else onSelect?.(d.id)}}>{cursor!==null&&<i className="playback-cursor" style={{left:cursor}}/>}{svg?<div className={activeId?'is-playing':''} dangerouslySetInnerHTML={{__html:svg}}/>:<div className="empty-staff"><span>건반을 눌러 모티프를 시작하세요</span></div>}</div>}
