import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, Check, ChevronDown, CircleHelp, ClipboardCopy, Clock3, Eraser, Link2, Pause, Play, Redo2, RotateCcw, Search, Trash2, Undo2 } from 'lucide-react';
import type { MatchResult, Meter, Query, QueryEvent, QueryMode } from './types';
import { pitchName } from './music/pitch';
import { Keyboard } from './components/Keyboard';
import { Notation } from './components/Notation';
import { ResultCard } from './components/ResultCard';
import { ContourPad } from './components/ContourPad';
import { HumInput } from './components/HumInput';
import { collapseTies } from './search/features';
import { FullScorePage } from './components/FullScorePage';

const seed:[number,number][]=[[60,1],[62,.5],[64,.5],[67,1]];
const DURATIONS=[.0625,.125,.25,.5,1,1.5,2,3,4];
const makeEvent=(pitchMidi:number|null,durationRatio=1):QueryEvent=>({id:`q-${crypto.randomUUID()}`,kind:pitchMidi===null?'rest':'note',pitchMidi,spelling:pitchMidi===null?undefined:pitchName(pitchMidi),durationRatio});
const restored=(()=>{try{const value=JSON.parse(sessionStorage.getItem('musicanote-search-state')||'null');return value?.schema===7?value:null}catch{return null}})();
export default function App(){return location.pathname==='/score'?<FullScorePage/>:<SearchApp/>}
function SearchApp(){
 const [events,setEvents]=useState<QueryEvent[]>(()=>restored?.events||seed.map(([p,d])=>makeEvent(p,d)));const [history,setHistory]=useState<QueryEvent[][]>([]);const [future,setFuture]=useState<QueryEvent[][]>([]);const [mode,setMode]=useState<QueryMode>(restored?.mode||'melody_rhythm');const [meter,setMeter]=useState<Meter>(restored?.meter||'4/4');const [selectedIds,setSelectedIds]=useState<string[]>([]);const [searched,setSearched]=useState(Boolean(restored?.searched));const [searching,setSearching]=useState(false);const [searchError,setSearchError]=useState('');const [results,setResults]=useState<{exact:MatchResult[];similar:MatchResult[]}>(restored?.results||{exact:[],similar:[]});const [playing,setPlaying]=useState(false);const [copied,setCopied]=useState(false);const timers=useRef<number[]>([]);
 const query:Query=useMemo(()=>({version:1,mode,meter,startsOnDownbeat:true,events}),[events,mode,meter]);
 useEffect(()=>{sessionStorage.setItem('musicanote-search-state',JSON.stringify({schema:7,events,mode,meter,searched,results}));},[events,mode,meter,searched,results]);
 useEffect(()=>{const y=Number(sessionStorage.getItem('musicanote-search-scroll')||0);if(y)requestAnimationFrame(()=>scrollTo(0,y))},[]);
 useEffect(()=>{const save=()=>sessionStorage.setItem('musicanote-search-scroll',String(scrollY));addEventListener('scroll',save,{passive:true});return()=>removeEventListener('scroll',save)},[]);
 const runSearch=async(searchQuery:unknown=query)=>{const effective=(searchQuery as Query)?.version===1?searchQuery as Query:query;setSearching(true);setSearchError('');setSearched(true);try{const response=await fetch('/api/search/v2/melody',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:effective,limit:20})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Search failed');setResults(data)}catch(error){setResults({exact:[],similar:[]});setSearchError(error instanceof Error?error.message:'Search failed')}finally{setSearching(false)}};
 const commit=(next:QueryEvent[])=>{setHistory(h=>[...h,events]);setFuture([]);setEvents(next)};const addNote=(m:number)=>commit([...events,makeEvent(m)]);const undo=()=>{const prev=history.at(-1);if(!prev)return;setFuture(f=>[events,...f]);setEvents(prev);setHistory(h=>h.slice(0,-1))};const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h,events]);setEvents(next);setFuture(f=>f.slice(1))};const removeEvent=()=>{if(!events.length)return;const targets=selectedIds.length?new Set(selectedIds):new Set([events.at(-1)!.id]);commit(events.filter(e=>!targets.has(e.id)));setSelectedIds([])};const clearQuery=()=>{if(events.length)commit([]);setSelectedIds([]);setPlaying(false);setSearched(false)};const toggleSelection=(id:string)=>setSelectedIds(ids=>ids.includes(id)?ids.filter(x=>x!==id):ids.length>=2?[ids[1],id]:[...ids,id]);const selectedForTie=selectedIds.map(id=>events.findIndex(e=>e.id===id)).sort((a,b)=>a-b);const canTie=selectedForTie.length===2&&selectedForTie[1]===selectedForTie[0]+1&&selectedForTie.every(i=>events[i]?.kind==='note')&&events[selectedForTie[0]]?.pitchMidi===events[selectedForTie[1]]?.pitchMidi;const tieSelected=()=>{if(!canTie)return;const group=`tie-${crypto.randomUUID()}`;commit(events.map((e,i)=>selectedForTie.includes(i)?{...e,tieGroup:group}:e));setSelectedIds([])};
 const copyQuery=async()=>{const portable={schema:'musicanote-query',query};try{await navigator.clipboard.writeText(JSON.stringify(portable,null,2));setCopied(true);window.setTimeout(()=>setCopied(false),1800)}catch{setSearchError('클립보드에 Query를 복사하지 못했습니다. 브라우저 권한을 확인해 주세요.')}};
 const play=()=>{timers.current.forEach(clearTimeout);if(playing){setPlaying(false);return;}setPlaying(true);let at=0;collapseTies(events).forEach(e=>{const ms=625*e.durationRatio;if(e.kind==='note')timers.current.push(window.setTimeout(()=>{setSelectedIds([e.id]);const ctx=new AudioContext(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=440*Math.pow(2,(e.pitchMidi!-69)/12);gain.gain.setValueAtTime(.08,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+Math.min(.5,ms/1000));osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+Math.min(.55,ms/1000))},at));at+=ms});timers.current.push(window.setTimeout(()=>{setPlaying(false);setSelectedIds([])},at))};
 return <div className="app"><header><a className="brand" href="#"><span className="brand-mark">M</span><span>MUSICANOTE<small>Similarity Search Lab</small></span></a><nav><a className="active" href="#search">Search</a><a href="#method">How it works</a><a href="#about">Archive</a></nav><button className="help"><CircleHelp size={17}/> 연구자 가이드</button></header>
 <main><section className="hero" id="search"><div><p className="kicker">MELODIC DISCOVERY, REIMAGINED</p><h1>기억 속 한 소절,<br/><em>그 너머까지.</em></h1></div><p className="hero-copy">음정이 같지 않아도, 리듬이 조금 달라도 괜찮습니다.<br/>선율의 흐름과 구조를 읽어 닮은 음악을 찾습니다.</p></section>
 <section className="composer"><div className="composer-head"><div><span className="step">01</span><h2>모티프를 입력하세요</h2><p>건반·오선·허밍으로 음표 4개 이상을 입력하세요.</p></div><div className="toolbar"><button onClick={undo} disabled={!history.length}><Undo2/> Undo</button><button onClick={redo} disabled={!future.length}><Redo2/> Redo</button><button onClick={tieSelected} disabled={!canTie} title="인접한 같은 음 두 개를 선택하세요"><Link2/> Tie</button><button onClick={copyQuery} disabled={!events.length} title="현재 Query를 JSON으로 클립보드에 복사">{copied?<Check/>:<ClipboardCopy/>} {copied?'Copied':'Copy Query'}</button><button onClick={removeEvent} disabled={!events.length} title={selectedIds.length?'선택한 이벤트 삭제':'마지막 이벤트 삭제'}><Trash2/> {selectedIds.length?'Delete selected':'Delete last'}</button><button onClick={clearQuery} disabled={!events.length}><Eraser/> Clear</button></div></div>
 <div className="notation-stage"><div className="duration-overlay" aria-label="음표별 음가 조절">{events.map((e,i)=>{const setDuration=(value:number)=>commit(events.map(v=>v.id===e.id?{...v,durationRatio:value}:v));const durationIndex=Math.max(0,DURATIONS.indexOf(e.durationRatio));return <div key={e.id} className={`duration-cell ${selectedIds.includes(e.id)?'selected':''} ${e.tieGroup?'tied':''}`} style={{flexGrow:Math.max(.25,e.durationRatio)}} onClick={()=>toggleSelection(e.id)}><div><b>{e.kind==='rest'?'Rest':e.spelling}{e.tieGroup?' ⌒':''}</b><span>{e.durationRatio} beat</span></div><input aria-label={`${i+1}번째 음 길이`} title={`${e.durationRatio} beat`} type="range" min="0" max={DURATIONS.length-1} step="1" value={durationIndex} onClick={x=>x.stopPropagation()} onChange={x=>setDuration(DURATIONS[+x.target.value])}/><div className="duration-steps"><button aria-label={`${i+1}번째 음 짧게`} onClick={x=>{x.stopPropagation();setDuration(DURATIONS[Math.max(0,durationIndex-1)])}} disabled={durationIndex===0}>−</button><button aria-label={`${i+1}번째 음 길게`} onClick={x=>{x.stopPropagation();setDuration(DURATIONS[Math.min(DURATIONS.length-1,durationIndex+1)])}} disabled={durationIndex===DURATIONS.length-1}>＋</button></div></div>})}</div><Notation query={query} activeId={selectedIds[0]} onSelect={toggleSelection} onPitchChange={(id,steps)=>commit(events.map(e=>e.id===id&&e.pitchMidi!==null?{...e,pitchMidi:Math.max(24,Math.min(108,e.pitchMidi+steps)),spelling:pitchName(Math.max(24,Math.min(108,e.pitchMidi+steps)))}:e))}/></div>
 <Keyboard onNote={addNote}/>
 <HumInput onNotes={pitches=>commit(pitches.map(p=>makeEvent(p)))}/>
{mode==='contour'&&<ContourPad onSearch={gesture=>void runSearch({...query,mode:'contour',events:gesture.map(item=>({...makeEvent(item.pitchMidi),contourShapeConfidence:item.contourShapeConfidence}))})}/>}
 <div className="controls"><div className="transport"><button className="round" onClick={play}>{playing?<Pause/>:<Play/>}</button><button className="round" onClick={()=>{setSelectedIds([]);setPlaying(false)}}><RotateCcw/></button><span><Clock3/> 96 BPM</span></div><button className="rest-btn" onClick={()=>commit([...events,makeEvent(null)])}>𝄽 <span>쉼표 추가</span></button><label>박자<select value={meter} onChange={e=>setMeter(e.target.value as Meter)}><option>4/4</option><option>3/4</option><option>6/8</option><option>unknown</option></select><ChevronDown/></label><div className="mode-toggle"><button className={mode==='melody'?'active':''} onClick={()=>setMode('melody')}>Melody only</button><button className={mode==='melody_rhythm'?'active':''} onClick={()=>setMode('melody_rhythm')}>Melody + Rhythm</button><button className={mode==='contour'?'active':''} onClick={()=>{setMode('contour');setSearched(false);setResults({exact:[],similar:[]})}}>Contour draw</button></div>{mode!=='contour'&&<button className="search-btn" disabled={searching||events.filter(e=>e.kind==='note').length<4} onClick={runSearch}><Search/> {searching?'Searching 8,111 works…':'닮은 음악 찾기'} <ArrowRight/></button>}</div>
 </section>
 {searched&&<section className="results"><div className="results-head"><div><span className="step">02</span><h2>검색 결과</h2></div><p><b>{results.exact.length+results.similar.length}</b>개의 작품에서 유사한 구간을 찾았습니다 <span>Exact 우선 · 작품별 최고 occurrence</span></p></div>{searchError&&<p className="search-error">{searchError}</p>}
 {results.exact.length>0&&<><div className="bucket-title"><b>Exact matches</b><span>{results.exact.length} result</span></div>{results.exact.map((r,i)=><ResultCard key={r.work.workId} result={r} index={i}/>)}</>}
 <div className="bucket-title"><b>Similar matches</b><span>{results.similar.length} results · 구조적 맥락 포함</span></div>{results.similar.map((r,i)=><ResultCard key={r.work.workId} result={r} index={i+results.exact.length}/>)}</section>}
 <section className="method" id="method"><p className="kicker">HOW THE MATCH IS MADE</p><h2>한 줄의 점수가 아니라,<br/>근거가 보이는 검색.</h2><div><article><span>1</span><h3>선율 특징 분리</h3><p>상대 음높이, 음정, 5단계 윤곽, 정규화된 리듬을 독립 특징으로 보존합니다.</p></article><article><span>2</span><h3>박자에 고정한 정렬</h3><p>마디 첫 박 후보만 비교하고 장식음은 낮은 gap 비용으로 처리합니다.</p></article><article><span>3</span><h3>구조적 맥락 보정</h3><p>지속, 강박, 화성 지지와 프레이즈 위치의 confidence가 충분할 때만 가중합니다.</p></article></div></section>
 </main><footer><div className="brand"><span className="brand-mark">M</span><span>MUSICANOTE</span></div><p>Similarity evidence for musical discovery.<br/>검색 결과는 저작권 침해에 대한 법률적 판단이 아닙니다.</p><span>SEARCH VERSION · similarity-v1</span></footer></div>}
