import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUp, Check, ChevronDown, CircleHelp, ClipboardCopy, Clock3, Eraser, Link2, Music2, Pause, Play, Redo2, RotateCcw, Search, SlidersHorizontal, Trash2, Undo2 } from 'lucide-react';
import type { MatchResult, Meter, Query, QueryEvent, QueryMode } from './types';
import { pitchName } from './music/pitch';
import { Keyboard } from './components/Keyboard';
import { Notation } from './components/Notation';
import { ResultCard } from './components/ResultCard';
import { ContourPad } from './components/ContourPad';
import { HumInput } from './components/HumInput';
import { collapseTies } from './search/features';
import { FullScorePage } from './components/FullScorePage';
import { CatalogSearch } from './components/CatalogSearch';
import { insertAfterSelection, stepSelectedDurations, transposeSelectedEvents } from './music/queryEdit';
import { schedulePhrase, warmPlayback, type ScheduledPlayback } from './music/audioPlayback';
import { rhythmGlyph } from './music/rhythmGlyph';

const seed:[number,number][]=[[60,1],[62,.5],[64,.5],[67,1]];
const DURATIONS=[.0625,.125,.25,.5,.75,1,1.5,2,3,4];
const makeEvent=(pitchMidi:number|null,durationRatio=1,preferFlat=false):QueryEvent=>({id:`q-${crypto.randomUUID()}`,kind:pitchMidi===null?'rest':'note',pitchMidi,spelling:pitchMidi===null?undefined:pitchName(pitchMidi,preferFlat),durationRatio});
const restored=(()=>{try{const value=JSON.parse(sessionStorage.getItem('musicanote-search-state')||'null');return value?.schema>=7?value:null}catch{return null}})();
export default function App(){return location.pathname==='/score'?<FullScorePage/>:<SearchApp/>}
function SearchApp(){
 const [preferFlat,setPreferFlat]=useState(Boolean(restored?.preferFlat));
 const [events,setEvents]=useState<QueryEvent[]>(()=>restored?.events||seed.map(([p,d])=>makeEvent(p,d)));const [history,setHistory]=useState<QueryEvent[][]>([]);const [future,setFuture]=useState<QueryEvent[][]>([]);const [mode,setMode]=useState<QueryMode>(restored?.mode||'melody_rhythm');const [meter,setMeter]=useState<Meter>(restored?.meter||'4/4');const [exactIntervalOnly,setExactIntervalOnly]=useState(Boolean(restored?.exactIntervalOnly??restored?.absoluteExactOnly));const [exactPitchOnly,setExactPitchOnly]=useState(Boolean(restored?.exactPitchOnly));const [exactRhythmOnly,setExactRhythmOnly]=useState(Boolean(restored?.exactRhythmOnly));const [includeRests,setIncludeRests]=useState(restored?.includeRests!==false);const [downbeatWeightBoost,setDownbeatWeightBoost]=useState(Boolean(restored?.downbeatWeightBoost));const [advancedOpen,setAdvancedOpen]=useState(Boolean(restored?.advancedOpen));const [searchWithinResults,setSearchWithinResults]=useState(Boolean(restored?.searchWithinResults));const [selectedIds,setSelectedIds]=useState<string[]>([]);const [tupletNormalOverride,setTupletNormalOverride]=useState<number|null>(null);const [searched,setSearched]=useState(Boolean(restored?.searched));const [searching,setSearching]=useState(false);const [searchRemaining,setSearchRemaining]=useState<number|null>(null);const [searchError,setSearchError]=useState('');const [results,setResults]=useState<{exact:MatchResult[];similar:MatchResult[]}>(restored?.results||{exact:[],similar:[]});const [corpusStats,setCorpusStats]=useState<{works:number;streams:number}|null>(null);const [playing,setPlaying]=useState(false);const [copied,setCopied]=useState(false);const timers=useRef<number[]>([]),playback=useRef<ScheduledPlayback|null>(null),searchCountdown=useRef<number|null>(null);
 const query:Query=useMemo(()=>({version:1,mode,meter,startsOnDownbeat:true,events,absoluteExactOnly:false,exactIntervalOnly:mode==='contour'||mode==='rhythm'?false:exactIntervalOnly,exactPitchOnly:mode==='contour'||mode==='rhythm'?false:exactPitchOnly,exactRhythmOnly:mode==='contour'?false:exactRhythmOnly,includeRests,downbeatWeightBoost:mode==='contour'||mode==='rhythm'?false:downbeatWeightBoost}),[events,mode,meter,exactIntervalOnly,exactPitchOnly,exactRhythmOnly,includeRests,downbeatWeightBoost]);
 useEffect(()=>{sessionStorage.setItem('musicanote-search-state',JSON.stringify({schema:8,events,mode,meter,preferFlat,exactIntervalOnly,exactPitchOnly,exactRhythmOnly,includeRests,downbeatWeightBoost,advancedOpen,searchWithinResults,searched,results}));},[events,mode,meter,preferFlat,exactIntervalOnly,exactPitchOnly,exactRhythmOnly,includeRests,downbeatWeightBoost,advancedOpen,searchWithinResults,searched,results]);
 useEffect(()=>{const y=Number(sessionStorage.getItem('musicanote-search-scroll')||0);if(y)requestAnimationFrame(()=>scrollTo(0,y))},[]);
 useEffect(()=>{const save=()=>sessionStorage.setItem('musicanote-search-scroll',String(scrollY));addEventListener('scroll',save,{passive:true});return()=>removeEventListener('scroll',save)},[]);
 useEffect(()=>{let live=true;fetch('/api/search/v2/stats').then(response=>response.ok?response.json():Promise.reject()).then(data=>{if(live)setCorpusStats(data)}).catch(()=>{});return()=>{live=false}},[]);
 useEffect(()=>{const warm=()=>warmPlayback();addEventListener('pointerdown',warm,{once:true});return()=>removeEventListener('pointerdown',warm)},[]);
 useEffect(()=>()=>{if(searchCountdown.current!==null)clearInterval(searchCountdown.current)},[]);
 const runSearch=async(searchQuery:unknown=query)=>{const base=(searchQuery as Query)?.version===1?searchQuery as Query:query,scopeWorkIds=searchWithinResults&&searched?[...results.exact,...results.similar].map(result=>result.work.workId):undefined,effective={...base,scopeWorkIds},noteCount=(base.events||[]).filter(event=>event.kind==='note').length,etaKey=`musicanote-search-eta:${base.mode}:${noteCount<8?'short':noteCount<16?'medium':'long'}:${scopeWorkIds?'scoped':'corpus'}`,fallback=scopeWorkIds?8:base.mode==='rhythm'?12:Math.min(45,18+noteCount*.7),estimated=Math.max(2,Number(localStorage.getItem(etaKey))||fallback),started=performance.now();if(searchCountdown.current!==null)clearInterval(searchCountdown.current);setSearchRemaining(Math.ceil(estimated));searchCountdown.current=window.setInterval(()=>{const elapsed=(performance.now()-started)/1000;setSearchRemaining(elapsed<estimated?Math.max(1,Math.ceil(estimated-elapsed)):0)},250);setSearching(true);setSearchError('');setSearched(true);try{const response=await fetch('/api/search/v2/melody',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:effective,limit:100})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Search failed');setResults(data)}catch(error){setResults({exact:[],similar:[]});setSearchError(error instanceof Error?error.message:'Search failed')}finally{const actual=Math.max(1,(performance.now()-started)/1000),learned=Math.max(2,Math.min(120,.65*estimated+.35*actual));localStorage.setItem(etaKey,learned.toFixed(1));if(searchCountdown.current!==null)clearInterval(searchCountdown.current);searchCountdown.current=null;setSearchRemaining(null);setSearching(false)}};
 const commit=(next:QueryEvent[])=>{setHistory(h=>[...h,events]);setFuture([]);setEvents(next)};const addNote=(m:number)=>commit([...events,makeEvent(m)]);const undo=()=>{const prev=history.at(-1);if(!prev)return;setFuture(f=>[events,...f]);setEvents(prev);setHistory(h=>h.slice(0,-1))};const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h,events]);setEvents(next);setFuture(f=>f.slice(1))};const removeEvent=()=>{if(!events.length)return;const targets=selectedIds.length?new Set(selectedIds):new Set([events.at(-1)!.id]);commit(events.filter(e=>!targets.has(e.id)));setSelectedIds([])};const clearQuery=()=>{if(events.length)commit([]);setSelectedIds([]);setPlaying(false);setSearched(false);setSearchWithinResults(false)};const toggleSelection=(id:string)=>{setTupletNormalOverride(null);setSelectedIds(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id])};const selectedIndexes=selectedIds.map(id=>events.findIndex(e=>e.id===id)).filter(i=>i>=0).sort((a,b)=>a-b);const selectedForTie=selectedIndexes;const canTie=selectedForTie.length===2&&selectedForTie[1]===selectedForTie[0]+1&&selectedForTie.every(i=>events[i]?.kind==='note')&&events[selectedForTie[0]]?.pitchMidi===events[selectedForTie[1]]?.pitchMidi;const tieSelected=()=>{if(!canTie)return;const group=`tie-${crypto.randomUUID()}`;commit(events.map((e,i)=>selectedForTie.includes(i)?{...e,tieGroup:group}:e));setSelectedIds([])};const suggestedTupletBase=(count:number)=>count===2?3:count===3?2:count>=5?4:3;const selectedEvents=selectedIndexes.map(i=>events[i]);const selectedWritten=selectedEvents.map(e=>e.writtenDuration??e.durationRatio),smallestWritten=Math.min(...selectedWritten),tupletActual=selectedEvents.length?Math.max(2,Math.round(selectedWritten.reduce((sum,value)=>sum+value,0)/smallestWritten)):0;const tupletNormal=tupletNormalOverride??suggestedTupletBase(tupletActual);const existingTuplet=selectedEvents.length>1&&Boolean(selectedEvents[0]?.tupletGroup)&&selectedEvents.every(e=>e.tupletGroup===selectedEvents[0].tupletGroup);const canTuplet=selectedIndexes.length>=2&&selectedIndexes.every((value,index)=>index===0||value===selectedIndexes[index-1]+1);const toggleTuplet=()=>{if(!canTuplet)return;if(existingTuplet){commit(events.map((e,i)=>selectedIndexes.includes(i)?{...e,durationRatio:e.writtenDuration??e.durationRatio,writtenDuration:undefined,tupletGroup:undefined,actualNotes:undefined,normalNotes:undefined}:e))}else{const actual=tupletActual,group=`tuplet-${crypto.randomUUID()}`;commit(events.map((e,i)=>{if(!selectedIndexes.includes(i))return e;const writtenDuration=e.writtenDuration??e.durationRatio;return{...e,writtenDuration,durationRatio:writtenDuration*tupletNormal/actual,tupletGroup:group,actualNotes:actual,normalNotes:tupletNormal}}))}setSelectedIds([]);setTupletNormalOverride(null)};
 const insertEvent=(event:QueryEvent)=>{commit(insertAfterSelection(events,selectedIds,event));setSelectedIds([event.id])};const addPreferredNote=(m:number)=>insertEvent(makeEvent(m,1,preferFlat));const changeAccidentalPreference=(flat:boolean)=>setPreferFlat(flat);
 const transposeSelection=(semitones:number)=>{if(!selectedIds.length)return;commit(transposeSelectedEvents(events,selectedIds,semitones,preferFlat))};
 const copyQuery=async()=>{const portable={schema:'musicanote-query',query};try{await navigator.clipboard.writeText(JSON.stringify(portable,null,2));setCopied(true);window.setTimeout(()=>setCopied(false),1800)}catch{setSearchError('클립보드에 Query를 복사하지 못했습니다. 브라우저 권한을 확인해 주세요.')}};
 const play=()=>{timers.current.forEach(clearTimeout);playback.current?.stop();if(playing){setPlaying(false);setSelectedIds([]);return;}const sounded=collapseTies(events);playback.current=schedulePhrase(sounded);setPlaying(true);let at=60;sounded.forEach(e=>{const ms=625*e.durationRatio;if(e.kind==='note')timers.current.push(window.setTimeout(()=>setSelectedIds([e.id]),at));at+=ms});timers.current.push(window.setTimeout(()=>{setPlaying(false);setSelectedIds([]);playback.current=null},at+80))};
 return <div className="app"><header><a className="brand" href="#"><span className="brand-mark">M</span><span>MUSICANOTE<small>Similarity Search Lab</small></span></a><nav><a className="active" href="#search">Search</a><a href="#method">How it works</a><a href="#about">Archive</a></nav><CatalogSearch/><button className="help"><CircleHelp size={17}/> 연구자 가이드</button></header>
 <main><section className="hero" id="search"><div><p className="kicker">MELODIC DISCOVERY, REIMAGINED</p><h1>기억 속 한 소절,<br/><em>그 너머까지.</em></h1></div><p className="hero-copy">음정이 같지 않아도, 리듬이 조금 달라도 괜찮습니다.<br/>선율의 흐름과 구조를 읽어 닮은 음악을 찾습니다.</p></section>
 <section className="composer"><div className="composer-head"><div><span className="step">01</span><h2>모티프를 입력하세요</h2><p>건반·오선·허밍으로 음표 4개 이상을 입력하세요.</p></div><div className="toolbar"><button onClick={undo} disabled={!history.length}><Undo2/> Undo</button><button onClick={redo} disabled={!future.length}><Redo2/> Redo</button><button onClick={tieSelected} disabled={!canTie} title="인접한 같은 음 두 개를 선택하세요"><Link2/> Tie</button><span className="tuplet-control"><select aria-label="Tuplet이 차지할 일반 음표 수" value={tupletNormal} onChange={event=>setTupletNormalOverride(Number(event.target.value))}><option value={2}>in 2</option><option value={3}>in 3</option><option value={4}>in 4</option></select><button onClick={toggleTuplet} disabled={!canTuplet} title="연속된 음표나 쉼표를 2개 이상 선택하세요">{existingTuplet?'Remove tuplet':`Tuplet ${tupletActual||'N'}:${tupletNormal}`}</button></span><button onClick={copyQuery} disabled={!events.length} title="현재 Query를 JSON으로 클립보드에 복사">{copied?<Check/>:<ClipboardCopy/>} {copied?'Copied':'Copy Query'}</button><button onClick={removeEvent} disabled={!events.length} title={selectedIds.length?'선택한 이벤트 삭제':'마지막 이벤트 삭제'}><Trash2/> {selectedIds.length?'Delete selected':'Delete last'}</button><button onClick={clearQuery} disabled={!events.length}><Eraser/> Clear</button></div></div>
 <div className="notation-stage"><div className="pitch-stepper" aria-label="선택 음표 반음 이동"><button onClick={()=>transposeSelection(1)} disabled={!selectedEvents.some(event=>event.kind==='note')} title="선택 음표를 반음 올리기" aria-label="선택 음표를 반음 올리기"><ArrowUp/></button><button onClick={()=>transposeSelection(-1)} disabled={!selectedEvents.some(event=>event.kind==='note')} title="선택 음표를 반음 내리기" aria-label="선택 음표를 반음 내리기"><ArrowDown/></button></div><div className="duration-overlay" aria-label="음표별 음가 조절">{events.map((e,i)=>{const writtenDuration=e.writtenDuration??e.durationRatio;const setDuration=(value:number)=>commit(events.map(v=>v.id===e.id?{...v,writtenDuration:v.tupletGroup?value:undefined,durationRatio:v.tupletGroup?value*(v.normalNotes||2)/(v.actualNotes||3):value}:v));const durationIndex=Math.max(0,DURATIONS.indexOf(writtenDuration));return <div key={e.id} className={`duration-cell ${selectedIds.includes(e.id)?'selected':''} ${e.tieGroup?'tied':''} ${e.tupletGroup?'tuplet':''}`} style={{flexGrow:Math.max(.25,e.durationRatio)}} onClick={()=>toggleSelection(e.id)}><div><b>{e.kind==='rest'?'Rest':e.spelling}{e.tieGroup?' ⌒':''}</b><span>{e.tupletGroup?`${writtenDuration} beat · ${e.actualNotes}:${e.normalNotes}`:`${e.durationRatio} beat`}</span></div><input aria-label={`${i+1}번째 음 길이`} title={`${writtenDuration} written beat${e.tupletGroup?` (${e.durationRatio.toFixed(3)} sounding)`:''}`} type="range" min="0" max={DURATIONS.length-1} step="1" value={durationIndex} onClick={x=>x.stopPropagation()} onChange={x=>setDuration(DURATIONS[+x.target.value])}/><div className="duration-steps"><button aria-label={`${i+1}번째 음 짧게`} onClick={x=>{x.stopPropagation();commit(stepSelectedDurations(events,selectedIds,e.id,DURATIONS,-1))}} disabled={durationIndex===0}>−</button><button aria-label={`${i+1}번째 음 길게`} onClick={x=>{x.stopPropagation();commit(stepSelectedDurations(events,selectedIds,e.id,DURATIONS,1))}} disabled={durationIndex===DURATIONS.length-1}>＋</button></div></div>})}</div>{mode==='rhythm'?<div className="rhythm-line" aria-label="리듬 전용 Query">{events.map(event=><button key={event.id} className={selectedIds.includes(event.id)?'selected':''} style={{flexGrow:Math.max(.25,event.durationRatio)}} onClick={()=>toggleSelection(event.id)} aria-label={`${event.kind==='rest'?'쉼표':'음표'} ${event.writtenDuration??event.durationRatio}박`}><span>{rhythmGlyph(event)}</span>{event.tupletGroup&&<small>{event.actualNotes}:{event.normalNotes}</small>}<i/></button>)}</div>:<Notation query={query} activeId={selectedIds[0]} onSelect={toggleSelection} onPitchChange={(id,steps)=>commit(events.map(e=>e.id===id&&e.pitchMidi!==null?{...e,pitchMidi:Math.max(24,Math.min(108,e.pitchMidi+steps)),spelling:pitchName(Math.max(24,Math.min(108,e.pitchMidi+steps)))}:e))}/>}</div>
 <Keyboard onNote={addPreferredNote} preferFlat={preferFlat} onPreferenceChange={changeAccidentalPreference}/>
 <HumInput onNotes={pitches=>commit(pitches.map(p=>makeEvent(p,1,preferFlat)))}/>
{mode==='contour'&&<ContourPad onSearch={gesture=>void runSearch({...query,mode:'contour',events:gesture.map(item=>({...makeEvent(item.pitchMidi),contourShapeConfidence:item.contourShapeConfidence}))})}/>}
 <div className="controls"><div className="transport"><button className="round" onClick={play}>{playing?<Pause/>:<Play/>}</button><button className="round" onClick={()=>{setSelectedIds([]);setPlaying(false)}}><RotateCcw/></button><span><Clock3/> 96 BPM</span></div><button className="rest-btn" onClick={()=>insertEvent(makeEvent(null))}><b className="rest-glyph">𝄽</b> <span>Insert Rest</span></button><button className="rest-btn" onClick={()=>insertEvent(makeEvent(60,1,preferFlat))}><Music2/> <span>Insert Note</span></button><label>박자<select value={meter} onChange={e=>setMeter(e.target.value as Meter)}><option>2/4</option><option>3/4</option><option>4/4</option><option>5/4</option><option>3/8</option><option>6/8</option><option>7/8</option><option>9/8</option><option>12/8</option><option>unknown</option></select><ChevronDown/></label><div className="mode-toggle"><button className={mode==='melody'?'active':''} onClick={()=>setMode('melody')}>Melody only</button><button className={mode==='melody_rhythm'?'active':''} onClick={()=>setMode('melody_rhythm')}>Melody + Rhythm</button><button className={mode==='rhythm'?'active':''} onClick={()=>setMode('rhythm')}>Rhythm only</button><button className={mode==='contour'?'active':''} onClick={()=>{setMode('contour');setSearched(false);setResults({exact:[],similar:[]});setSearchWithinResults(false)}}>Contour draw</button></div>{mode!=='contour'&&<button className="search-btn" disabled={searching||(mode==='rhythm'?events.length:events.filter(e=>e.kind==='note').length)<4} onClick={runSearch}><Search/> {searching?(corpusStats?`Searching ${corpusStats.works.toLocaleString()} works · ${searchRemaining===0?'마무리 중…':searchRemaining===null?'예상 시간 계산 중…':`${searchRemaining}초 남음`}`:(searchRemaining===0?'검색 마무리 중…':`검색 중 · ${searchRemaining??'…'}초 남음`)):'닮은 음악 찾기'} <ArrowRight/></button>}</div>
 {mode!=='contour'&&<div className="advanced-search"><button className="advanced-toggle" onClick={()=>setAdvancedOpen(open=>!open)} aria-expanded={advancedOpen}><SlidersHorizontal/> 상세 검색 <ChevronDown className={advancedOpen?'open':''}/></button>{advancedOpen&&<div className="query-options"><label className={mode==='rhythm'?'disabled':''}><input type="checkbox" checked={exactIntervalOnly} disabled={mode==='rhythm'} onChange={event=>setExactIntervalOnly(event.target.checked)}/><span><b>Exact Interval</b><small>조옮김을 허용하고 음정열이 완전히 같은 결과</small></span></label><label className={mode==='rhythm'?'disabled':''}><input type="checkbox" checked={exactPitchOnly} disabled={mode==='rhythm'} onChange={event=>setExactPitchOnly(event.target.checked)}/><span><b>Exact Pitch</b><small>옥타브를 포함한 실제 음높이가 완전히 같은 결과</small></span></label><label><input type="checkbox" checked={exactRhythmOnly} onChange={event=>setExactRhythmOnly(event.target.checked)}/><span><b>Exact Rhythm</b><small>전체 확대·축소를 허용하고 음가 비율이 같은 결과</small></span></label><label><input type="checkbox" checked={includeRests} onChange={event=>setIncludeRests(event.target.checked)}/><span><b>Include Rests</b><small>끄면 Query의 쉼표 길이를 검색 비교에서 제외</small></span></label><label className={mode==='rhythm'?'disabled':''}><input type="checkbox" checked={downbeatWeightBoost} disabled={mode==='rhythm'} onChange={event=>setDownbeatWeightBoost(event.target.checked)}/><span><b>Strengthen Downbeat Weight</b><small>Downbeat 가중치 4배 적용</small></span></label><label className={!searched||results.exact.length+results.similar.length===0?'disabled':''}><input type="checkbox" checked={searchWithinResults} disabled={!searched||results.exact.length+results.similar.length===0} onChange={event=>setSearchWithinResults(event.target.checked)}/><span><b>Search Within Results</b><small>현재 결과 작품 안에서 수정한 Query로 다시 검색</small></span></label></div>}</div>}
 </section>
 {searched&&<section className="results"><div className="results-head"><div><span className="step">02</span><h2>검색 결과</h2></div><p><b>{results.exact.length+results.similar.length}</b>개의 작품에서 유사한 구간을 찾았습니다 <span>Exact 우선 · 작품별 최고 occurrence</span></p></div>{searchError&&<p className="search-error">{searchError}</p>}
 {results.exact.length>0&&<><div className="bucket-title"><b>Exact matches</b><span>{results.exact.length} result</span></div>{results.exact.map((r,i)=><ResultCard key={r.work.workId} result={r} index={i}/>)}</>}
 <div className="bucket-title"><b>Similar matches</b><span>{results.similar.length} results · 구조적 맥락 포함</span></div>{results.similar.map((r,i)=><ResultCard key={r.work.workId} result={r} index={i+results.exact.length}/>)}</section>}
 <section className="method" id="method"><p className="kicker">HOW THE MATCH IS MADE</p><h2>한 줄의 점수가 아니라,<br/>근거가 보이는 검색.</h2><div><article><span>1</span><h3>선율 특징 분리</h3><p>상대 음높이, 음정, 5단계 윤곽, 정규화된 리듬을 독립 특징으로 보존합니다.</p></article><article><span>2</span><h3>박자에 고정한 정렬</h3><p>마디 첫 박 후보만 비교하고 장식음은 낮은 gap 비용으로 처리합니다.</p></article><article><span>3</span><h3>구조적 맥락 보정</h3><p>지속, 강박, 화성 지지와 프레이즈 위치의 confidence가 충분할 때만 가중합니다.</p></article></div></section>
 </main><footer><div className="brand"><span className="brand-mark">M</span><span>MUSICANOTE</span></div><p>Similarity evidence for musical discovery.<br/>검색 결과는 저작권 침해에 대한 법률적 판단이 아닙니다.</p><span>SEARCH VERSION · similarity-v1</span></footer></div>}
